### ISSUE TITLE
Missing key/value pairs in setShapeProperties(dict) method of QgsPoint3DSymbol() class 

### ISSUE THREAD

**Issue by AbdelghaniTamort** [qgis/pyqgis-api-docs-builder#140]
The documentation doesn't provide the key/value pairs of each shape property of 3D point symbol : [docs](https://qgis.org/pyqgis/3.36/_3d/QgsPoint3DSymbol.html#qgis._3d.QgsPoint3DSymbol.setShapeProperties)
![image](https://github.com/qgis/pyqgis/assets/118017108/5b528711-e262-4d66-a2f5-8a33ec5e4251)

For example I chose to work with the model shape (qgis.analysis.Qgis.Point3DShape(7)) then I would need to define the path to the model using the setShapeProperties() method. However I have no indication to which key in the input dictionnary I would need.

**Comment by 3nids** [comment]
There is no more documentation in the cpp file, see https://github.com/qgis/QGIS/blob/79285c27c2ce342ab1267c72d2b02b767d4b32e4/src/3d/symbols/qgspoint3dsymbol.h#L110

One of the dev needs to fill this. Maybe the author @wonder-sk

**Comment by AbdelghaniTamort** [comment]
Is it scheduled to be added to the docs?
