### ISSUE TITLE
Grenoble link to doc "File not found"

### ISSUE THREAD

**Issue by cspwcspw** [qgis/pyqgis-api-docs-builder#143]
Start Grenoble.  Start the python console.  
>>> _pyqgis

launches a browser to  https://qgis.org/pyqgis/3.38/ 
which says "File not found"  (index.html)

**Comment by 3nids** [comment]
almost there, give me day

**Comment by cspwcspw** [comment]
No problem.    If I ignore the 3.38 version-specific suffix in the url and go instead to https://qgis.org/pyqgis I get the "master" documentation link.    Perhaps an automatic server-side redirect to "master" if a specific documentation version is not available would be cool.

**Comment by DelazJ** [comment]
FYI 3.38 docs is online. And if I understand @3nids recent improvements, the next docs should be built (more) automatically after release. Is the redirection still necessary? Afaik there is already a redirection to master for uneven version numbers...

**Comment by DelazJ** [comment]
BTW, @3nids the 3.38 zip link in https://qgis.org/pyqgis/master/#versions-of-the-api (in "Earlier versions of the documentation are also available as downloads") does not work. not formatted as others.
