### ISSUE TITLE
Wrong indentation in some class parameters description

### ISSUE THREAD

**Issue by nicogodet** [qgis/pyqgis-api-docs-builder#165]
https://qgis.org/pyqgis/master/core/QgsMapLayer.html#module-QgsMapLayer
https://qgis.org/pyqgis/master/core/QgsVectorLayer.html#module-QgsVectorLayer
https://qgis.org/pyqgis/master/core/QgsMeshLayer.html#module-QgsMeshLayer

**Comment by nyalldawson** [comment]
This is fixed by https://github.com/qgis/pyqgis-api-docs-builder/pull/167
