### ISSUE TITLE
overloaded methods

### ISSUE THREAD

**Issue by 3nids** [qgis/pyqgis-api-docs-builder#18]
Go to https://qgis.org/pyqgis/master/core/Layout/QgsLayoutExporter.html#qgis.core.QgsLayoutExporter.exportToPdf
The exportToPdf has more than one way to call it but only the one in the grayed area (next to the name) is obvious, and when looking for a function you may miss the other alternative. This is also true for exportToImage, exportToSVG, print... (at least in this class).
Moreover, the paragraph showing the second alternative does not look sexy to read and you want to skip it (I unfortunately did it (!) for hours until I find in the github repo what I was looking for, which is not the way we want people to proceed.).

**Comment by 3nids** [comment]
https://github.com/sphinx-doc/sphinx/issues/2106

I don't see any solution for this at the moment except reimplementing autodoc

**Comment by kannes** [comment]
> [sphinx-doc/sphinx#2106](https://github.com/sphinx-doc/sphinx/issues/2106)

This issue has been closed as implemented and it seems that overloaded functions can now be handled by Sphinx. :))

**Comment by kannes** [comment]
Yeah, that looks the same as before to me :(

It looks like support was again improved in Sphinx 4.0: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_docstring_signature

I don't know what the input of that is and if it fits what Sphinx expects.

**Comment by 3nids** [comment]
by reading a bit, found this: https://sphinx-toolbox.readthedocs.io/en/latest/extensions/more_autodoc/overloads.html

**Comment by 3nids** [comment]
@nyalldawson do you have any hints/thoughts on this one?

**Comment by kannes** [comment]
Oh this looks great now!

![image](https://github.com/user-attachments/assets/9339227a-cacc-45f7-b0bb-f0f9533e0c23)
