### ISSUE TITLE
Incorrect visualization of constructors (e.g. QgsField: __init__(name: str | None = '', type: QMetaType.Type = ..... )

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/pyqgis-api-docs-builder#185]
In master / 3.38 / 3.34 https://qgis.org/pyqgis/master/core/QgsField.html#qgis.core.QgsField:

![image](https://github.com/user-attachments/assets/7ab81025-36fc-41a2-949e-26be3b3c300d)

Previously https://web.archive.org/web/20240518153401/https://qgis.org/pyqgis/3.34/core/QgsField.html#qgis.core.QgsField:

![image](https://github.com/user-attachments/assets/8d0291f0-af35-44e7-a84b-68a608483771)

**Comment by nyalldawson** [comment]
The new version is correct. Whats the issue here?

**Comment by agiudiceandrea** [comment]
In my opinion it was more clear before
`QgsField(name: str = ‘’, type: QVariant.Type = QVariant.Invalid, typeName: str = ‘’, len: int = 0, prec: int = 0, comment: str = ‘’, subType: QVariant.Type = QVariant.Invalid) `

than now
`__init__(name: str | None = '', type: QVariant.Type = QVariant.Invalid, typeName: str | None = '', len: int = 0, prec: int = 0, comment: str | None = '', subType: QVariant.Type = QVariant.Invalid)`

but it probably depends on the fact that I got used to it.
