### ISSUE TITLE
Show inheritance diagram

### ISSUE THREAD

**Issue by nyalldawson** [qgis/pyqgis-api-docs-builder#76]
... using https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html or similar. The class inheritance diagram is extremely useful in the C++ docs and I'd love to see one included in the python docs too.

**Comment by AHB102** [comment]
I have some doubts, can we discuss ?

**Comment by DelazJ** [comment]
@AHB102 please share your doubts. No permission required first. Thanks.
